import type { AutoGeneratedSection } from "./types.js";

const BEGIN_MARKER = "BEGIN_AUTO_GENERATED";
const END_MARKER = "END_AUTO_GENERATED";

export class AutoGeneratedHandler {
  /**
   * コンテンツからBEGIN_AUTO_GENERATED/END_AUTO_GENERATED部分を抽出
   */
  static extractAutoGeneratedSection(content: string): AutoGeneratedSection {
    const beginIndex = content.indexOf(BEGIN_MARKER);
    const endIndex = content.indexOf(END_MARKER);

    if (beginIndex === -1 || endIndex === -1) {
      return {
        before: content,
        content: "",
        after: "",
        found: false,
      };
    }

    if (beginIndex >= endIndex) {
      throw new Error(
        "BEGIN_AUTO_GENERATED must appear before END_AUTO_GENERATED",
      );
    }

    const beginMarkerEnd = beginIndex + BEGIN_MARKER.length;
    const before = content.substring(0, beginIndex + BEGIN_MARKER.length);
    const autoGeneratedContent = content.substring(beginMarkerEnd, endIndex);
    const after = content.substring(endIndex);

    return {
      before,
      content: autoGeneratedContent,
      after,
      found: true,
    };
  }

  /**
   * 自動生成部分を新しいコンテンツで置き換え
   */
  static replaceAutoGeneratedSection(
    originalContent: string,
    newGeneratedContent: string,
  ): string {
    const section =
      AutoGeneratedHandler.extractAutoGeneratedSection(originalContent);

    if (!section.found) {
      // マーカーが見つからない場合は、末尾に追加
      return `${originalContent}

<p>${BEGIN_MARKER}</p>
<p>${newGeneratedContent}</p>
<p>${END_MARKER}</p>`;
    }

    // マーカー間の内容を置き換え（太字継承を防ぐため、pタグで囲む）
    return `${section.before}
<p>${newGeneratedContent}</p>
${section.after}`;
  }

  /**
   * 自動生成部分のみを取得
   */
  static getAutoGeneratedContent(content: string): string {
    const section = AutoGeneratedHandler.extractAutoGeneratedSection(content);
    return section.content.trim();
  }

  /**
   * マーカーが存在するかチェック
   */
  static hasAutoGeneratedMarkers(content: string): boolean {
    return content.includes(BEGIN_MARKER) && content.includes(END_MARKER);
  }

  /**
   * マーカーを含む自動生成セクションを作成
   */
  static createAutoGeneratedSection(content: string): string {
    return `<p>${BEGIN_MARKER}</p>
<p>${content}</p>
<p>${END_MARKER}</p>`;
  }
}
