import type { AxiosInstance } from "axios";
import axios from "axios";
import { logger } from "./logger.js";
import type {
  ConfluenceConfig,
  ConfluencePage,
  PageUpdateRequest,
} from "./types.js";

export class ConfluenceClient {
  private api: AxiosInstance;

  constructor(config: ConfluenceConfig) {
    this.api = axios.create({
      baseURL: `${config.baseUrl}/wiki/rest/api`,
      auth: {
        username: config.email,
        password: config.apiToken,
      },
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
    });
  }

  /**
   * ページIDからページ情報を取得
   */
  async getPage(pageId: string): Promise<ConfluencePage> {
    const startTime = Date.now();
    const url = `/content/${pageId}`;

    logger.apiStart("GET", url, pageId);

    try {
      const response = await this.api.get(url, {
        params: {
          expand: "body.storage,version",
        },
      });

      const responseTime = Date.now() - startTime;
      logger.apiComplete("GET", response.status, responseTime);

      return response.data;
    } catch (error) {
      const responseTime = Date.now() - startTime;

      if (axios.isAxiosError(error)) {
        const status = error.response?.status || 0;
        logger.apiError("GET", status, error, responseTime);

        throw new Error(
          `Failed to get page ${pageId}: ${status} ${error.response?.statusText || error.message}`,
        );
      }

      logger.apiError(
        "GET",
        0,
        error instanceof Error ? error : new Error(String(error)),
        responseTime,
      );
      throw error;
    }
  }

  /**
   * ページを更新
   */
  async updatePage(
    pageId: string,
    title: string,
    content: string,
    version: number,
  ): Promise<ConfluencePage> {
    const startTime = Date.now();
    const url = `/content/${pageId}`;

    logger.apiStart("PUT", url, pageId);

    const updateRequest: PageUpdateRequest = {
      id: pageId,
      type: "page",
      title,
      body: {
        storage: {
          value: content,
          representation: "storage",
        },
      },
      version: {
        number: version + 1,
        message: "auto-generated by mcp-confluence-demo",
      },
    };

    try {
      const response = await this.api.put(url, updateRequest);

      const responseTime = Date.now() - startTime;
      logger.apiComplete("PUT", response.status, responseTime);

      return response.data;
    } catch (error) {
      const responseTime = Date.now() - startTime;

      if (axios.isAxiosError(error)) {
        const status = error.response?.status || 0;
        logger.apiError("PUT", status, error, responseTime);

        throw new Error(
          `Failed to update page ${pageId}: ${status} ${error.response?.statusText || error.message}`,
        );
      }

      logger.apiError(
        "PUT",
        0,
        error instanceof Error ? error : new Error(String(error)),
        responseTime,
      );
      throw error;
    }
  }

  /**
   * URLからページIDを抽出
   */
  static extractPageIdFromUrl(url: string): string {
    const match = url.match(/\/pages\/(\d+)\//);
    if (!match || !match[1]) {
      throw new Error(`Cannot extract page ID from URL: ${url}`);
    }
    return match[1];
  }
}
