export interface ConfluenceConfig {
  baseUrl: string;
  email: string;
  apiToken: string;
}

export interface ConfluencePage {
  id: string;
  title: string;
  body: {
    storage: {
      value: string;
      representation: string;
    };
  };
  version: {
    number: number;
  };
}

export interface PageUpdateRequest {
  id: string;
  type: string;
  title: string;
  body: {
    storage: {
      value: string;
      representation: string;
    };
  };
  version: {
    number: number;
    message?: string;
  };
}

export interface AutoGeneratedSection {
  before: string;
  content: string;
  after: string;
  found: boolean;
}

/**
 * Options for external I/O operations
 * Supports timeout and cancellation via AbortSignal
 */
export interface IOOptions {
  /**
   * AbortSignal for cancellation from caller
   */
  signal?: AbortSignal;
  /**
   * Timeout in milliseconds (default: 10000ms)
   */
  timeoutMs?: number;
}
