export interface ConfluenceConfig {
  baseUrl: string;
  email: string;
  apiToken: string;
}

export interface ConfluencePage {
  id: string;
  title: string;
  body: {
    storage: {
      value: string;
      representation: string;
    };
  };
  version: {
    number: number;
  };
}

export interface PageUpdateRequest {
  id: string;
  type: string;
  title: string;
  body: {
    storage: {
      value: string;
      representation: string;
    };
  };
  version: {
    number: number;
    message?: string;
  };
}

export interface AutoGeneratedSection {
  before: string;
  content: string;
  after: string;
  found: boolean;
}

/**
 * Options for external I/O operations
 * Supports timeout and cancellation via AbortSignal
 */
export interface IOOptions {
  /**
   * AbortSignal for cancellation from caller
   */
  signal?: AbortSignal;
  /**
   * Timeout in milliseconds (default: 10000ms)
   */
  timeoutMs?: number;
}

/**
 * Image reference in Markdown
 */
export interface ImageReference {
  originalPath: string; // Markdownでの参照パス
  resolvedPath: string; // 実際のファイルパス（絶対パス）
  alt: string;
  attributes?: {
    width?: number;
    height?: number;
  }; // <img>タグの属性
}

/**
 * Confluence image reference
 */
export interface ConfluenceImageReference {
  filename: string;
  downloadUrl: string;
}

/**
 * Confluence attachment information
 */
export interface AttachmentInfo {
  id: string;
  title: string; // ファイル名
  downloadUrl: string;
  fileSize: number;
  mediaType: string;
  version?: number;
}

export interface AttachmentMeta {
  id: string;
  title: string;
  version: number;
  downloadedAt: string;
  storagePath: string;
  sha256: string;
  mediaType?: string;
  fileSize?: number;
  lastUploadedAt?: string;
}

export interface PageMeta {
  pageId: string;
  title: string;
  version: number;
  downloadedAt: string;
  storagePath: string;
  storageSha256: string;
  lastUploadedAt?: string;
  lastAttachmentScanAt?: string;
  attachments: AttachmentMeta[];
}

export interface ConfluenceDataPaths {
  baseDir: string;
  pageDir: string;
  pageFile: string;
  metaFile: string;
  attachmentsDir: string;
  logDir: string;
}

export interface BodyDownloadResult {
  success: boolean;
  skipped: boolean;
  pageFile: string;
  metaFile: string;
  logFiles: string[];
}

export interface BodyUploadResult {
  success: boolean;
  pageUpdated: boolean;
  metaFile: string;
  logFiles: string[];
}

export interface AttachmentsDownloadResult {
  success: boolean;
  downloaded: string[];
  skipped: string[];
  removed: string[];
  metaFile: string;
  logFiles: string[];
}

export interface AttachmentsUploadResult {
  success: boolean;
  uploaded: string[];
  skipped: string[];
  metaFile: string;
  logFiles: string[];
}

/**
 * Result of Markdown import operation
 */
export interface ImportResult {
  success: boolean;
  pageId: string;
  pageTitle: string;
  pageVersion: number;
  uploadedImages: string[]; // ファイル名のリスト（既存の場合は新バージョンとして追加）
}

/**
 * Result of Markdown export operation
 */
export interface ExportResult {
  success: boolean;
  markdownFile: string;
  downloadedImages: string[];
  outputDir: string;
}

/**
 * Validation result for image files
 */
export interface ValidationResult {
  valid: boolean;
  errors: ValidationError[];
}

/**
 * Validation error for image files
 */
export interface ValidationError {
  type: "not_found" | "size_limit" | "invalid_type";
  path: string;
  message: string;
}
